// LEX FORENSICA v8.0 — Operational Constants

import { OperationalAxiom, InstitutionType } from '../types';

// ---------------------------------------------------------------------------
// AXIOM_DEFINITIONS
// ---------------------------------------------------------------------------

export const AXIOM_DEFINITIONS: Record<
  OperationalAxiom,
  { name: string; description: string; legalBasis: string }
> = {
  [OperationalAxiom.A1_FORENSIC_SPOLIATION]: {
    name: 'Forensic Spoliation',
    description:
      'Absence of documentation does not equal absence of event. Missing records, destroyed files, or incomplete logs are treated as potential evidence of concealment. The burden falls on the institution to demonstrate that the undocumented period was uneventful, not on the subject to prove what was never written down.',
    legalBasis: 'ECHR Art. 3 (prohibition of inhuman treatment), ECHR Art. 13 (right to effective remedy)',
  },
  [OperationalAxiom.A2_SEMANTIC_NEUTRALIZATION]: {
    name: 'Semantic Neutralization',
    description:
      'Compliance-framing language in institutional records masks coercive acts behind neutral terminology. Any finding invoking behavioural compliance or non-compliance must be anchored to a specific incident date and context. Undated or decontextualised compliance claims are forensically void.',
    legalBasis: 'ECHR Art. 6 (right to a fair trial — requirement of reasoned decisions)',
  },
  [OperationalAxiom.A3_IATROGENIC_ATTRIBUTION]: {
    name: 'Iatrogenic Attribution',
    description:
      'Effects caused by institutional interventions (medication, detention conditions, procedural stress) must be distinguished from pre-existing symptoms. Conflating iatrogenic harm with underlying condition to justify continued intervention constitutes a logical and ethical breach.',
    legalBasis: 'ECHR Art. 3 (prohibition of inhuman or degrading treatment), CRPD Art. 25 (right to health on an equal basis)',
  },
  [OperationalAxiom.A4_EPISTEMIC_CIRCULARITY]: {
    name: 'Epistemic Circularity',
    description:
      'A diagnostic or legal conclusion that is immune to falsification — where any counter-evidence is reinterpreted as confirming the original hypothesis — is epistemically invalid. Such conclusions cannot ground judicial decisions or coercive interventions.',
    legalBasis: 'ECHR Art. 6(1) (right to fair trial — requirement of impartial and reasoned adjudication)',
  },
  [OperationalAxiom.A5_STRUCTURAL_BIAS]: {
    name: 'Structural Bias',
    description:
      'When a single expert or expert body conducts multiple sequential assessments in the same case — particularly in proceedings involving coercion — institutional bias is presumed. Each assessment reinforces prior framing rather than providing independent scrutiny. This structural arrangement violates the requirement of impartiality.',
    legalBasis: 'ECHR Art. 6(1) (requirement of an independent and impartial tribunal), CRPD Art. 12 (equal recognition before the law)',
  },
  [OperationalAxiom.A6_JUDICIAL_ABANDONMENT]: {
    name: 'Judicial Abandonment',
    description:
      'When a court delegates its substantive decision-making power to expert opinion without exercising independent legal review — particularly in liberty-restricting proceedings — it abdicates its constitutional function. The judge must assess legal criteria independently; expert opinion informs but cannot replace judicial reasoning.',
    legalBasis: 'ECHR Art. 5(4) (right to review of lawfulness of detention), ECHR Art. 6(1) (right to determination by an independent tribunal)',
  },
};

// ---------------------------------------------------------------------------
// INSTITUTION_PATTERNS
// ---------------------------------------------------------------------------

export const INSTITUTION_PATTERNS: Record<
  InstitutionType,
  {
    complianceTerms: string[];
    expertTitles: string[];
    judicialBodies: string[];
  }
> = {
  [InstitutionType.PSYCHIATRIC]: {
    complianceTerms: [
      'treatment adherence',
      'medication compliance',
      'insight into illness',
      'lack of insight',
      'cooperative behaviour',
      'therapeutic alliance',
      'risk to self or others',
      'capacity to consent',
      'voluntary admission',
      'involuntary commitment',
      'stabilisation',
      'behavioural dysregulation',
      'non-compliant with treatment',
      'refuses medication',
      'absconded from ward',
      'elopement risk',
      'danger to self',
      'psychotic episode',
      'decompensation',
      'chronic course of illness',
    ],
    expertTitles: [
      'Consultant Psychiatrist',
      'Forensic Psychiatrist',
      'Clinical Psychologist',
      'Approved Mental Health Professional (AMHP)',
      'Responsible Clinician',
      'Psychiatrický znalec',
      'Soudní znalec v oboru psychiatrie',
      'Facharzt für Psychiatrie und Psychotherapie',
      'Gutachter (Psychiatrie)',
      'Sachverständiger',
    ],
    judicialBodies: [
      'Mental Health Tribunal',
      'First-tier Tribunal (Mental Health)',
      'Okresní soud (opatrovnické řízení)',
      'Krajský soud',
      'Betreuungsgericht',
      'Amtsgericht (Betreuung)',
      'Court of Protection',
      'Magistrates Court (MHA)',
      'Psychiatric Review Board',
    ],
  },

  [InstitutionType.JUDICIAL]: {
    complianceTerms: [
      'cooperation with authorities',
      'breach of bail conditions',
      'failure to appear',
      'contempt of court',
      'non-compliance with court order',
      'obstruction of justice',
      'lack of remorse',
      'risk of reoffending',
      'public interest',
      'proportionality of sanction',
      'procedural irregularity',
      'admissibility of evidence',
      'standard of proof',
      'beyond reasonable doubt',
      'balance of probabilities',
    ],
    expertTitles: [
      'Forensic Expert',
      'Court-appointed Expert',
      'Independent Expert Witness',
      'Soudní znalec',
      'Gerichtsgutachter',
      'Sachverständiger',
      'Legal Assessor',
      'Amicus Curiae',
    ],
    judicialBodies: [
      'District Court',
      'Regional Court',
      'Court of Appeal',
      'Supreme Court',
      'Okresní soud',
      'Krajský soud',
      'Nejvyšší soud',
      'Amtsgericht',
      'Landgericht',
      'Oberlandesgericht',
      'Bundesgerichtshof',
      'European Court of Human Rights',
    ],
  },

  [InstitutionType.ADMINISTRATIVE]: {
    complianceTerms: [
      'administrative non-compliance',
      'failure to submit required documentation',
      'procedural default',
      'regulatory breach',
      'non-fulfilment of statutory obligations',
      'failure to cooperate with inspection',
      'disregard of administrative decision',
      'abuse of administrative process',
      'frivolous submission',
      'vexatious complainant',
      'excess of authority',
      'ultra vires act',
    ],
    expertTitles: [
      'Administrative Law Judge',
      'Hearing Officer',
      'Správní úředník',
      'Referent',
      'Vedoucí odboru',
      'Sachbearbeiter',
      'Verwaltungsrichter',
      'Ombudsman',
      'Public Law Expert',
    ],
    judicialBodies: [
      'Administrative Court',
      'Správní soud',
      'Krajský soud – správní úsek',
      'Nejvyšší správní soud',
      'Verwaltungsgericht',
      'Oberverwaltungsgericht',
      'Bundesverwaltungsgericht',
      'Parliamentary Ombudsman',
      'Veřejný ochránce práv',
    ],
  },

  [InstitutionType.IMMIGRATION]: {
    complianceTerms: [
      'irregular entry',
      'overstay',
      'abscondment risk',
      'failure to comply with removal directions',
      'no legitimate expectation to remain',
      'credibility concerns',
      'inconsistent account',
      'safe third country',
      'manifestly unfounded claim',
      'Dublin regulation transfer',
      'non-cooperation with return',
      'identity not established',
      'lack of documentation',
      'voluntary departure',
      'administrative detention justified',
    ],
    expertTitles: [
      'Immigration Judge',
      'Asylum Decision Maker',
      'Country of Origin Information Analyst',
      'Referát azylového řízení',
      'Pracovník OAMP',
      'BAMF Entscheider',
      'Asylrichter',
      'UNHCR Resettlement Officer',
      'Immigration Enforcement Officer',
    ],
    judicialBodies: [
      'First-tier Tribunal (Immigration and Asylum)',
      'Upper Tribunal (Immigration and Asylum Chamber)',
      'Krajský soud (azylová agenda)',
      'Nejvyšší správní soud',
      'Verwaltungsgericht (Asylrecht)',
      'Bundesamt für Migration und Flüchtlinge (BAMF)',
      'CJEU',
      'ECtHR',
    ],
  },

  [InstitutionType.CUSTODIAL]: {
    complianceTerms: [
      'breach of prison rules',
      'adjudication finding',
      'failure to comply with officer instructions',
      'disruptive behaviour',
      'disciplinary segregation',
      'risk assessment (ARMS/OASys)',
      'enhanced supervision',
      'refusal to engage with offending behaviour programme',
      'negative drug test',
      'earned privilege level',
      'parole suitability',
      'licence conditions breach',
      'recall to custody',
    ],
    expertTitles: [
      'Offender Manager',
      'Probation Officer',
      'Prison Governor',
      'Forensic Psychologist',
      'OASys Assessor',
      'Vězeňský psycholog',
      'Koordinátor výkonu trestu',
      'Vollzugsbeamter',
      'Bewährungshelfer',
      'Forensischer Psychologe',
    ],
    judicialBodies: [
      'Parole Board',
      'Prison Adjudication Panel',
      'Independent Monitoring Board',
      'Soud pro výkon trestu',
      'Krajský soud (podmíněné propuštění)',
      'Strafvollstreckungskammer',
      'Landgericht (Vollstreckung)',
    ],
  },

  [InstitutionType.REGULATORY]: {
    complianceTerms: [
      'regulatory non-compliance',
      'licence condition breach',
      'market abuse',
      'failure of fit and proper test',
      'inadequate systems and controls',
      'data protection breach',
      'misleading regulator',
      'obstruction of regulatory process',
      'lack of candour',
      'fitness to practise impaired',
      'conduct unbecoming',
      'professional misconduct',
    ],
    expertTitles: [
      'Regulatory Inspector',
      'Compliance Officer',
      'Fitness to Practise Panel Member',
      'Regulatory Adjudicator',
      'Živnostenský inspektor',
      'Inspektor ČNB',
      'BaFin-Prüfer',
      'Marktaufseher',
      'FCA Enforcement Officer',
    ],
    judicialBodies: [
      'Regulatory Tribunal',
      'Medical Practitioners Tribunal Service (MPTS)',
      'Fitness to Practise Panel',
      'Financial Services Tribunal',
      'Správní soud (regulace)',
      'Finanzgericht',
      'Verwaltungsgericht (Gewerbe)',
    ],
  },

  [InstitutionType.MEDICAL_GENERAL]: {
    complianceTerms: [
      'patient compliance',
      'adherence to treatment plan',
      'informed consent obtained',
      'capacity assessment required',
      'best interests decision',
      'clinical necessity',
      'risk-benefit analysis',
      'contraindicated by patient behaviour',
      'discharge against medical advice',
      'failed follow-up',
      'did not attend (DNA)',
      'non-engagement with services',
    ],
    expertTitles: [
      'Consultant Physician',
      'General Practitioner',
      'Clinical Lead',
      'Medical Director',
      'Obvodní lékař',
      'Primář',
      'Ošetřující lékař',
      'Niedergelassener Arzt',
      'Facharzt',
      'Leitender Arzt',
    ],
    judicialBodies: [
      'Court of Protection',
      'Coroners Court',
      'NHS Complaints Adjudication',
      'Health Service Ombudsman',
      'Zdravotnický ombudsman',
      'Soud (opatrovnictví)',
      'Betreuungsgericht',
      'Ärztegericht',
    ],
  },

  [InstitutionType.CHILD_PROTECTIVE]: {
    complianceTerms: [
      'threshold criteria met',
      'significant harm',
      'risk of harm',
      'parental non-compliance with care plan',
      'failure to protect',
      'lack of parental insight',
      'non-engagement with services',
      'volatile home environment',
      'child in need',
      'looked after child',
      'placement breakdown',
      'contact refusal',
      'alienating behaviour',
      'child at risk of exploitation',
      'neglect indicators',
    ],
    expertTitles: [
      'Social Worker',
      'Independent Social Worker (ISW)',
      'Guardian ad Litem / Cafcass Officer',
      'Child Psychologist',
      'Paediatrician (Safeguarding)',
      'Sociální pracovník OSPOD',
      'Znalec z oboru pediatrie',
      'Znalec z oboru dětské psychologie',
      'Jugendamtsmitarbeiter',
      'Sachverständiger (Kindeswohl)',
      'Verfahrensbeistand',
    ],
    judicialBodies: [
      'Family Court',
      'High Court (Family Division)',
      'Okresní soud (rodinná agenda)',
      'Krajský soud',
      'Familiengericht',
      'Oberlandesgericht (Familie)',
      'Jugendamt',
      'CAFCASS',
    ],
  },

  [InstitutionType.OTHER]: {
    complianceTerms: [
      'non-compliance with institutional requirements',
      'failure to follow procedure',
      'breach of applicable standards',
      'lack of cooperation',
      'procedural non-conformity',
      'failure to engage',
      'disregard of institutional authority',
      'refusal to comply',
    ],
    expertTitles: [
      'Appointed Expert',
      'Institutional Assessor',
      'Independent Reviewer',
      'Znalec',
      'Gutachter',
      'Sachverständiger',
    ],
    judicialBodies: [
      'Competent Court',
      'Příslušný soud',
      'Zuständiges Gericht',
      'Tribunal',
      'Ombudsman',
      'Review Panel',
    ],
  },
};

// ---------------------------------------------------------------------------
// SLANG_MAP
// ---------------------------------------------------------------------------

export const SLANG_MAP: Record<'cs' | 'en' | 'de', Record<string, string>> = {
  cs: {
    // Psychiatric / medical
    bágr: 'pacient pod silnou sedací medikací',
    blázinec: 'psychiatrická nemocnice / psychiatrické oddělení',
    cvokárna: 'psychiatrické oddělení',
    chcanky: 'psychiatrické oddělení (hovorově)',
    paciák: 'pacient (hovorový výraz)',
    šrotit: 'podávat vysoké dávky antipsychotik',
    zombík: 'pacient ve stavu farmakologické apatie',
    chlapáci_v_bílém: 'zdravotnický personál',
    prášky: 'léky',
    tabletky: 'léky ve formě tablet',
    injeknout: 'aplikovat injekci',
    propustit: 'ukončit hospitalizaci',
    zavřít: 'hospitalizovat bez souhlasu',
    dát_do_ústavu: 'umístit do ústavní péče',
    patopsycho: 'patopsychologické vyšetření',
    // Judicial / custodial
    basa: 'věznice',
    buchta: 'dozorce / vězeňský strážník',
    flek: 'trest odnětí svobody / rozsudek',
    kriminál: 'věznice / kriminální případ',
    natáhnout: 'prodloužit výkon vazby nebo trestu',
    prásknout: 'udat / informovat orgány',
    sedět: 'vykonávat trest odnětí svobody',
    vazba: 'vyšetřovací vazba',
    obháje: 'obhájce',
    znalák: 'soudní znalec',
    // Administrative / institutional
    byrokracie: 'administrativní překážky záměrně kladené',
    kolotoč: 'nekonečná administrativní smyčka',
    mlýnek: 'institucionální systém odírající žadatele',
    papírování: 'nadměrná dokumentační povinnost',
    přihrávat: 'předávat případ mezi úřady bez řešení',
    razítko: 'formální souhlas bez věcného přezkumu',
    šuplíkovat: 'odkládat rozhodnutí bez termínu',
    natáhnout_koze_ruku: 'podat žalobu',
    vytáhnout_z_průšvihu: 'poskytnout právní pomoc',
    přepsat_historii: 'retroaktivně měnit dokumentaci',
  },
  en: {
    // Psychiatric / medical
    'psych ward': 'psychiatric inpatient unit',
    'loony bin': 'psychiatric facility',
    nuthouse: 'psychiatric facility',
    mental: 'psychiatric',
    shrink: 'psychiatrist',
    shrinks: 'psychiatrists',
    'pill pusher': 'prescribing physician',
    'pill pushers': 'prescribing physicians',
    script: 'prescription',
    scripts: 'prescriptions',
    meds: 'medications',
    dope: 'controlled substance',
    shot: 'injection',
    jab: 'injection',
    commit: 'involuntarily admit to psychiatric facility',
    sectioned: 'detained under mental health legislation',
    'baker acted': 'involuntarily examined under emergency psychiatric hold',
    '5150': 'involuntary psychiatric hold (72-hour)',
    boarded: 'involuntarily committed to a psychiatric unit',
    "benzo'd": 'sedated with benzodiazepines',
    'chemical restraint': 'use of medication to restrict movement or behaviour',
    'frequent flyer': 'repeated involuntary admissions — used dismissively',
    'revolving door': 'repeated short admissions without treatment continuity',
    straightjacketed: 'physically or chemically restrained',
    'lock up': 'secure psychiatric unit',
    'locked up': 'confined in secure facility',
    crazy: 'experiencing mental health symptoms',
    nuts: 'experiencing mental health symptoms',
    bonkers: 'experiencing mental health symptoms',
    // Medical professionals
    doc: 'physician',
    docs: 'physicians',
    quack: 'clinician of disputed competence',
    chart: 'medical record',
    charts: 'medical records',
    // Legal / judicial
    'lawyer up': 'retain legal counsel',
    sue: 'institute legal proceedings',
    cop: 'law enforcement officer',
    cops: 'law enforcement officers',
    guard: 'security officer',
    guards: 'security officers',
    file: 'legal or medical file',
    complaint: 'formal complaint',
    'rat out': 'report to authorities',
    snitched: 'reported to authorities',
    coverup: 'concealment of evidence',
    'cover-up': 'concealment of evidence',
    // Institutional / systemic
    bounced: 'application rejected without substantive review',
    churned: 'processed through the system without individual consideration',
    'fast-tracked': 'accelerated procedure with reduced procedural safeguards',
    flagged: 'placed on institutional watchlist',
    rubberstamped: 'approved without genuine scrutiny',
    stonewalled: 'denied access to information or process',
    'kicked upstairs': 'escalated to avoid local accountability',
    'managed out': 'pressured to disengage from services',
    'paper over': 'obscure systemic failure with documentation',
    'sign off': 'formal approval — may lack genuine review',
    'cover your ass': 'documentation designed to protect institution not subject',
  },
  de: {
    // Psychiatric / medical
    klaps: 'psychiatrische Einrichtung',
    klapsmühle: 'psychiatrische Klinik',
    irrenhaus: 'psychiatrische Anstalt (historischer Begriff)',
    nervenklinik: 'psychiatrische Klinik',
    zwangsjacke: 'mechanische oder chemische Fixierung',
    ruhiggestellt: 'medikamentös sediert (verschleiernd)',
    eingewiesen: 'zwangseingewiesen in psychiatrische Einrichtung',
    abteilung: 'psychiatrische Station (euphemistisch)',
    absitzen_psychiatrie: 'Psychiatrieaufenthalt passiv verbringen',
    pillendreher: 'Apotheker',
    knochen: 'Arzt',
    weißkittel: 'Arzt oder medizinisches Fachpersonal',
    spritzen: 'Injektionen verabreichen',
    tabletten: 'Medikamente in Tablettenform',
    zelle: 'Isolierraum',
    // Judicial / custodial
    bau: 'Gefängnis (umgangssprachlich)',
    knast: 'Gefängnis (umgangssprachlich)',
    'drin sitzen': 'in Haft sein',
    einsitzer: 'Einzelhaft',
    abschieben: 'zwangsweise verlegen oder abschieben',
    wegschließen: 'in geschlossener Einrichtung unterbringen',
    einsperren: 'in geschlossener Einrichtung unterbringen',
    weggesperrt: 'inhaftiert oder zwangsuntergebracht',
    bulle: 'Polizeibeamter',
    bullen: 'Polizeibeamte',
    // Administrative / institutional
    amtsdeutsch: 'bürokratische Sprache zur Verschleierung von Entscheidungen',
    behördenmarathon: 'endlose Behördengänge ohne Ergebnis',
    durchgewunken: 'ohne inhaltliche Prüfung genehmigt',
    formfehler: 'angeblicher Formfehler zur Umgehung des Sachgehalts',
    hinhaltetaktik: 'bewusste Verzögerung durch Behörde',
    papiertiger: 'Vorschrift ohne praktische Wirkung',
    schublade: 'Akte ohne Bearbeitung abgelegt',
    stempel: 'formale Genehmigung ohne inhaltliche Prüfung',
    verwaltet: 'ohne echte Fürsorge im System untergebracht',
    zuständigkeitspingpong: 'Weiterschieben zwischen Behörden ohne Lösung',
    // Social / identity
    abgehängt: 'systemischer Ausschluss von institutionellen Schutzansprüchen',
    'schwierige person': 'Begriff für rechtsbewusste Personen',
    irre: 'Person mit psychischen Erkrankungen (abwertend)',
    verrückt: 'psychisch beeinträchtigt (umgangssprachlich)',
    durchgeknallt: 'psychisch beeinträchtigt (abwertend)',
    bekloppt: 'psychisch beeinträchtigt (abwertend)',
    // Legal
    klagen: 'klagen vor Gericht',
    beschwerde: 'Beschwerde oder Klage',
    gutachter: 'Sachverständiger',
    sachverständiger: 'gerichtlich bestellter Sachverständiger',
    akte: 'Gerichts- oder Verwaltungsakte',
    akten: 'Gerichts- oder Verwaltungsakten',
    zeuge: 'Zeuge',
    zeugen: 'Zeugen',
  },
};

// ---------------------------------------------------------------------------
// PARAFRAME_MAP
// ---------------------------------------------------------------------------

export const PARAFRAME_MAP: Record<string, string> = {
  // Compliance and behaviour
  'non-compliant': 'Subject exercises autonomy over their own body or choices',
  noncompliant: 'Subject exercises autonomy over their own body or choices',
  uncooperative: "Subject declined to participate in procedures whose consent basis is disputed",
  'non-compliance with treatment': 'Subject declines intervention they did not meaningfully consent to',
  'lacks insight': 'Subject disagrees with institutional interpretation of their condition',
  'lacks insight into illness': "Clinician asserted diagnostic authority to override subject's self-report — epistemic circularity risk",
  'limited insight into illness': 'Subject contests the diagnostic framing applied to them',
  'poor insight': 'Subject maintains an account of events that contradicts institutional narrative',
  'insight-impaired': "Clinician attributed epistemic deficiency to subject to justify override of subject's expressed will",
  'refuses medication': 'Subject exercises the right to refuse medical intervention',
  'refuses treatment': 'Subject exercises the right to refuse medical intervention',
  'treatment resistant': 'Treatment has failed; institution attributes failure to subject',
  'medication-resistant': 'Subject did not respond to prescribed protocol; protocol suitability not reassessed',
  'treatment-resistant': 'Subject did not respond to prescribed protocol; protocol suitability not reassessed',
  'not engaging with services': 'Subject has withdrawn trust from institution following prior harm',
  'failed to engage': 'Subject was excluded from or rendered unable to use services',
  'does not comply with care plan': 'Subject has not consented to the plan imposed on them',
  resistant: 'Subject maintained position contrary to institutional preference',
  belligerent: 'Subject resisted institutional authority — context of coercion not documented',

  // Risk and dangerousness
  'risk to self or others': 'Catch-all phrase used to justify deprivation of liberty without specific evidence',
  'elevated risk': 'Risk framing used to override subject autonomy without measurable threshold',
  'risk cannot be ruled out': 'Absence of evidence used as affirmative justification for restriction',
  'poses a danger to society': 'Speculative prediction substituting for evidenced individual assessment',
  'flight risk': 'Subject is likely to exercise freedom of movement',
  'elopement risk': 'Subject may leave an institution they did not choose to enter',
  'at risk of deterioration': 'Institution predicts harm from withdrawal of its own intervention',
  'danger to self': 'Risk assertion made by institutional actor without documented independent assessment',
  'danger to others': 'Risk assertion made by institutional actor without documented independent assessment',
  'gravely disabled': 'Functional assessment performed by interested party; independent evaluation absent',

  // Capacity and autonomy
  'lacks capacity': 'Subject disagrees with proposed intervention; institutional override invoked',
  'unable to make an informed decision': 'Subject has been assessed as incapable of the very disagreement they are expressing',
  'best interests decision': 'Decision made on behalf of subject in which subject had no meaningful participation',
  'voluntary admission': 'Admission obtained under implicit or explicit coercive pressure',
  'voluntary patient': 'Admission characterised as voluntary; degree of coercion and informed consent not verified',
  'consented to treatment': 'Consent may have been given under conditions of confinement or dependency',
  'needs treatment': 'Treatment necessity asserted without documented independent second opinion',
  'requires hospitalization': 'Hospitalisation deemed necessary by actor who benefits from the determination',
  'requires inpatient care': 'Inpatient care deemed necessary by actor who benefits from the determination',

  // Diagnostic and clinical language
  'chronic course of illness': 'Longitudinal institutionalisation presented as natural disease trajectory',
  'chronic condition': 'Long-term diagnostic framing applied; course altered by institutional intervention not excluded',
  decompensation: 'Subject deteriorated, possibly due to institutional conditions or medication effects',
  'behavioural dysregulation': 'Subject responded visibly to an adverse or coercive environment',
  'emotional dysregulation': 'Subject expressed distress in a context designed to produce compliance',
  psychotic: 'Diagnostic label applied; differential diagnosis and adverse drug effect excluded',
  'psychotic episode': 'Acute crisis framed exclusively within disease model; context excluded',
  delusional: "Subject's claims classified as pathological without independent fact-checking",
  paranoid: 'Subject expressed distrust of institutional actors — institutional conduct not independently reviewed',
  stabilised: 'Sedated or rendered passive; baseline behaviour suppressed',
  improved: 'Subject now conforms to institutional expectations of acceptable behaviour',
  deteriorated: 'Subject resists, protests, or ceases to comply with institutional demands',
  'poor prognosis': 'Negative outcome prediction issued by treating clinician with vested interest',
  agitated: 'Subject exhibited distress response; iatrogenic origin not excluded',
  agitation: 'Subject exhibited distress response; iatrogenic origin not excluded',
  aggressive: 'Subject exhibited distress response; iatrogenic origin not excluded',

  // Documentation and procedure
  'no formal complaint was received': 'Subject was not informed of complaint mechanisms, or complaints were not recorded',
  'no concerns were documented at the time': 'Records reflect institutional perspective; subject experience may differ',
  'reviewed and no action required': 'Internal review without independent oversight',
  'thoroughly investigated': 'Investigation conducted by same institution being scrutinised',
  'assessment was proportionate': 'Conclusion stated without methodology that would allow verification',
  'consistent with clinical guidelines': 'Procedure was formally compliant; substantive harm not addressed',
  'multi-disciplinary team decision': 'Diffusion of individual accountability across team structure',
  'in accordance with policy': 'Policy compliance used to preclude substantive ethical review',

  // Social and identity framing
  'difficult patient': 'Patient who questions decisions, asserts rights, or reports harm',
  'challenging behaviour': 'Subject behaviour that creates institutional inconvenience',
  'attention-seeking': 'Distress signals that have been dismissed as manipulative',
  manipulative: 'Subject uses communication strategies to meet needs institution does not address',
  splitting: 'Subject has different relationships with different staff; framed as pathology',
  'socially isolated': 'Subject has been socially isolated by institutional placement',
  'poor social functioning': 'Subject has been deskilled or isolated by institutional processes',
  'cultural difference noted': 'Subject identity is pathologised or used to discount testimony',
  'language barrier': 'Subject denied access to interpretation; institutional failure attributed to subject',

  // Legal and quasi-legal
  'no legal remedy available': 'Institutional assessment of legal routes; subject may have been given incorrect information',
  'frivolous complaint': 'Complaint that challenges institutional conduct has been dismissed before examination',
  'vexatious litigant': 'Subject who persistently asserts rights that institutions prefer not to address',
  'matter has been concluded': 'Decision made by institution without independent appeal mechanism offered',
  'exhausted all available options': 'Institution-defined menu of options; may exclude human rights remedies',
  'frivolous submission': 'Submission dismissed without substantive engagement; institution characterises challenge as abuse of process',

  // Czech institutional equivalents
  nespolupracuje: 'Subjekt odmítl spolupracovat — dobrovolnost a informovaný souhlas neověřeny',
  odmítá: 'Subjekt uplatnil právo na odmítnutí — právní základ pro přehlasování není doložen',
  'chybí náhled': 'Klinický pracovník přisoudil epistemický deficit subjektu za účelem přehlasování jeho vůle',
  'nemá náhled': 'Klinický pracovník přisoudil epistemický deficit subjektu za účelem přehlasování jeho vůle',
  neochota: 'Subjekt projevil odpor vůči institucionálnímu postupu — kontext nátlaku není zdokumentován',
  agresivní: 'Subjekt projevil distres; iatrogenní původ není vyloučen',
  'popírá nemoc': 'Subjekt zpochybnil diagnózu; nezávislé ověření tvrzení subjektu neproběhlo',
  'nebezpečný sobě': 'Tvrzení o riziku vzneseno institucionálním aktérem bez nezávislého posouzení',
  'nebezpečný okolí': 'Tvrzení o riziku vzneseno institucionálním aktérem bez nezávislého posouzení',
  'potřebuje léčbu': 'Nezbytnost léčby tvrzena bez zdokumentovaného nezávislého druhého názoru',
  nemocný: 'Diagnostická nálepka aplikována; diferenciální diagnóza a nežádoucí účinky léků nevyloučeny',

  // German institutional equivalents
  verweigert: 'Subjekt hat von Verweigerungsrecht Gebrauch gemacht — Rechtsgrundlage für Überstimmung nicht belegt',
  'mangelnde compliance': 'Subjekt übte Recht auf Verweigerung der Behandlung gemäß Patientenautonomie aus',
  'fehlende krankheitseinsicht': "Kliniker hat dem Subjekt epistemisches Defizit zugeschrieben, um dessen geäußerten Willen zu überstimmen",
  'fehlende einsicht': "Kliniker hat dem Subjekt epistemisches Defizit zugeschrieben, um dessen geäußerten Willen zu überstimmen",
  unkooperativ: 'Subjekt lehnte institutionelle Anforderungen ab — Kontext des Zwangs nicht dokumentiert',
  aggressiv: 'Subjekt zeigte Distress-Reaktion; iatrogener Ursprung nicht ausgeschlossen',
  behandlungsbedürftig: 'Behandlungsnotwendigkeit behauptet ohne belegtes unabhängiges Zweitgutachten',
  'selbst- und fremdgefährdend': 'Risikobeschreibung durch institutionellen Akteur ohne unabhängige Bewertung',
  therapieresistent: 'Subjekt sprach nicht auf vorgeschriebenes Protokoll an; Protokolleignung nicht neu bewertet',
};
